import type { Copy, Lang } from './types'

export const copy: Record<Lang, Copy> = {
  no: {
    languageAction: 'English',
    languageName: 'Norsk',
    languageFlag: '🇳🇴',
    monthlyIncome: 'Månedlig inntekt',
    yearlySalary: 'Årslønn',
    expectedTax: 'Forventet skatt',
    disposable: 'Tilgjengelig etter skatt',
    burnRate: 'Forbruk',
    subscriptions: 'Abonnementer',
    incomeStreams: 'Inntektsstrømmer',
    debt: 'Gjeld',
    calendar: 'Kalender',
    monthOverview: 'Månedsoversikt',
    optimisticFuture: 'Optimistisk fremtid',
    add: 'Legg til',
    emptyEnv: 'Legg private tall i web/.env lokalt.',
    emptyList: 'Ingen linjer ennå.',
    placeholder: 'Skriv inn en ting',
    amountPlaceholder: 'Beløp',
    debtPlaceholder: 'Kredittkort, studielån, venn ...',
    calendarPlaceholder: 'Ikke-penger: trening, frist, avtale ...',
    selectedDay: 'Valgt dag',
    projectedBuffer: 'mulig buffer',
    projectedDebt: 'mulig gjeld',
    month: 'måned',
    days: ['Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør', 'Søn'],
  },
  en: {
    languageAction: 'Norsk',
    languageName: 'English',
    languageFlag: '🇬🇧',
    monthlyIncome: 'Monthly income',
    yearlySalary: 'Yearly salary',
    expectedTax: 'Expected tax',
    disposable: 'Available after tax',
    burnRate: 'Burn rate',
    subscriptions: 'Subscriptions',
    incomeStreams: 'Income streams',
    debt: 'Debt',
    calendar: 'Calendar',
    monthOverview: 'Month overview',
    optimisticFuture: 'Optimistic future',
    add: 'Add',
    emptyEnv: 'Add private numbers to web/.env locally.',
    emptyList: 'No lines yet.',
    placeholder: 'Write one thing',
    amountPlaceholder: 'Amount',
    debtPlaceholder: 'Credit card, student loan, friend ...',
    calendarPlaceholder: 'Non-money: workout, deadline, appointment ...',
    selectedDay: 'Selected day',
    projectedBuffer: 'potential buffer',
    projectedDebt: 'potential debt',
    month: 'month',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  },
}
